# Generated by Django 5.2.1 on 2025-06-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='observacao',
            new_name='descricao',
        ),
    ]
