# Generated by Django 5.2.1 on 2025-06-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_observacao_computador_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='computador_status',
            field=models.CharField(choices=[('Em Funcionamento', 'Funcionando'), ('Em Manutencao', 'Manutencao'), ('Desativado', 'Desativado')], default='Em Funcionamento', max_length=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='equipameto_status',
            field=models.CharField(choices=[('Em Funcionamento', 'Funcionando'), ('Em Manutencao', 'Manutencao'), ('Desativado', 'Desativado')], default='Em Funcionamento', max_length=50),
        ),
    ]
