# Generated by Django 5.2.1 on 2025-06-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manutencaocomputador_manutencaoequipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaocomputador',
            name='computador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='api.computador'),
        ),
        migrations.AlterField(
            model_name='manutencaocomputador',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='api.equipamento'),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_equipamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
