# Generated by Django 5.2.1 on 2025-06-20 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_manutencaocomputador_computador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaocomputador',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_equipamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
