# Generated by Django 5.2.1 on 2025-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_manutencaocomputador_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaocomputador',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
