# Generated by Django 5.2.1 on 2025-06-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_manutencaocomputador_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaocomputador',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='data',
            field=models.DateField(),
        ),
    ]
