# Generated by Django 5.2.1 on 2025-06-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_manutencaocomputador_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencaocomputador',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='manutencaoequipamento',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='manutencaocomputador',
            name='tipo_manutencao',
            field=models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva'), ('Atualizacao', 'Atualizacao')], default='Preventiva', max_length=100),
        ),
        migrations.AddField(
            model_name='manutencaoequipamento',
            name='tipo_manutencao',
            field=models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva'), ('Atualizacao', 'Atualizacao')], default='Preventiva', max_length=100),
        ),
    ]
