# Generated by Django 5.2.1 on 2025-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_manutencaocomputador_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='computador_status',
            field=models.CharField(choices=[('Em_Funcionamento', 'Funcionando'), ('Em_Manutencao', 'Manutencao'), ('Desativado', 'Desativado')], default='Em_Funcionamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equipameto_status',
            field=models.CharField(choices=[('Em_Funcionamento', 'Funcionando'), ('Em_Manutencao', 'Manutencao'), ('Desativado', 'Desativado')], default='Em_Funcionamento', max_length=50),
        ),
    ]
