# Generated by Django 5.2.1 on 2025-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_computador_computador_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='computador_status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Manutencao', 'Manutencao'), ('Desativado', 'Desativado')], default='Ativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equipameto_status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Manutencao', 'Manutencao'), ('Desativado', 'Desativado')], default='Ativo', max_length=50),
        ),
    ]
