# Generated by Django 5.2.1 on 2025-06-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_computador_computador_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='equipameto_status',
            new_name='equipamento_status',
        ),
    ]
