# Generated by Django 5.2.1 on 2025-06-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_equipameto_status_equipamento_equipamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='numero_de_telefone',
        ),
    ]
