# Generated by Django 5.2.1 on 2025-06-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_usuario_numero_de_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
