# Generated by Django 5.2.1 on 2025-06-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_usuario_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
    ]
