# Generated by Django 5.2.1 on 2025-06-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_usuario_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaocomputador',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manutencaoequipamento',
            name='data',
            field=models.DateField(),
        ),
    ]
