# Generated by Django 5.2.1 on 2025-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_manutencaocomputador_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='memoria_ram',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computador',
            name='modelo_hd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computador',
            name='modelo_ssd',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
