# Generated by Django 5.2.1 on 2025-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_computador_memoria_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
