version: "1.0"

services:
  frontend:
    image: abaco_frontend:latest
    build: ./teste
    ports:
      - 5173:5173
    container_name: abaco_frontend

  backend:
    image: abaco_backend:latest
    build: ./Backend
    ports:
      - 8000:8000
    container_name: abaco_backend

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: abaco
    ports:
      - 5432:5432
    container_name: abaco_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
