# Generated by Django 5.2.1 on 2025-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('numero_de_patrimonio', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('modelo_processador', models.CharField(max_length=100)),
                ('modelo_placa_mae', models.CharField(max_length=100)),
                ('modelo_placa_video', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('armazenamento', models.CharField(max_length=100)),
            ],
        ),
    ]
