# Generated by Django 5.2.1 on 2025-05-12 11:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('numero_de_patrimonio', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('modelo_processador', models.CharField(max_length=100)),
                ('modelo_placa_mae', models.CharField(max_length=100)),
                ('modelo_placa_video', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('armazenamento', models.CharField(max_length=100)),
                ('modelo_fonte', models.CharField(max_length=100)),
                ('modelo_gabinete', models.CharField(max_length=100)),
                ('modelo_hd', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('data_ultima_atualizacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('numero_de_patrimonio', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tecnico', 'Tecnico')], default='tecnico', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes_Computadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('Computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='api.computador')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes_Equipamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='api.equipamento')),
            ],
        ),
    ]
