# Generated by Django 5.2.1 on 2025-05-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('numero_de_patrimonio', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('modelo_processador', models.CharField(max_length=100)),
                ('modelo_placa_mae', models.CharField(max_length=100)),
                ('modelo_placa_video', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('armazenamento', models.CharField(max_length=100)),
                ('modelo_fonte', models.CharField(max_length=100)),
                ('modelo_gabinete', models.CharField(max_length=100)),
                ('modelo_hd', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('data_ultima_atualizacao', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('numero_de_patrimonio', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes_Computadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('Computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.computador')),
            ],
        ),
        migrations.AddField(
            model_name='computador',
            name='manutencoes',
            field=models.ManyToManyField(blank=True, to='api.manutencoes_computadores'),
        ),
        migrations.CreateModel(
            name='Manutencoes_Equipamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('Equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipamento')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='manutencoes',
            field=models.ManyToManyField(blank=True, to='api.manutencoes_equipamentos'),
        ),
    ]
