# Generated by Django 5.2.1 on 2025-05-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='manutencoes',
            field=models.ManyToManyField(to='api.manutencoes_computadores'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='manutencoes',
            field=models.ManyToManyField(to='api.manutencoes_equipamentos'),
        ),
    ]
