# Generated by Django 5.2.1 on 2025-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_de_telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
