# Generated by Django 5.2.1 on 2025-05-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_computador_manutencoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='manutencoes',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='manutencoes',
        ),
    ]
