from django.core.management.base import BaseCommand
from api.models import Computador, Equipamento, Manutencoes_Computadores, Manutencoes_Equipamentos

class Command(BaseCommand):
    help = 'Popular a tabela de máquinas'

    def handle(slef, *args, **kwargs):

        computadores = [
            Computador(
            numero_de_patrimonio="A_001",
            modelo_processador="Intel Core i7",
            modelo_placa_mae="Asus ROG Strix",
            modelo_placa_video="NVIDIA GeForce RTX 3080",
            memoria_ram="32GB",
            armazenamento="1TB SSD",
            modelo_fonte="Corsair 750W",
            modelo_gabinete="NZXT H510",
            modelo_hd="Seagate Barracuda 2TB",
            localizacao="Sala de Servidores",
            data_aquisicao="2023-01-01",
            ),
            Computador(
            numero_de_patrimonio="A_002",
            modelo_processador="Intel Core i5",
            modelo_placa_mae="Gigabyte Aorus",
            modelo_placa_video="NVIDIA GeForce GTX 1660",
            memoria_ram="16GB",
            armazenamento="512GB SSD",
            modelo_fonte="EVGA 600W",
            modelo_gabinete="Cooler Master Q300L",
            modelo_hd="Western Digital Blue 1TB",
            localizacao="Escritório 1",
            data_aquisicao="2023-02-01",
            ),
            Computador(
            numero_de_patrimonio="A_003",
            modelo_processador="AMD Ryzen 7",
            modelo_placa_mae="MSI B450 TOMAHAWK",
            modelo_placa_video="AMD Radeon RX 6700 XT",
            memoria_ram="32GB",
            armazenamento="1TB SSD",
            modelo_fonte="Seasonic 750W",
            modelo_gabinete="Fractal Design Meshify C",
            modelo_hd="Seagate Barracuda 2TB",
            localizacao="Sala de Reuniões",
            data_aquisicao="2023-03-01",
            ),
            Computador(
            numero_de_patrimonio="A_004",
            modelo_processador="Intel Core i9",
            modelo_placa_mae="ASRock Z590 Extreme",
            modelo_placa_video="NVIDIA GeForce RTX 3090",
            memoria_ram="64GB",
            armazenamento="2TB SSD",
            modelo_fonte="Corsair 850W",
            modelo_gabinete="Lian Li PC-O11",
            modelo_hd="Western Digital Black 4TB",
            localizacao="Sala de TI",
            data_aquisicao="2023-04-01",
            ),
            Computador(
            numero_de_patrimonio="A_005",
            modelo_processador="AMD Ryzen 5",
            modelo_placa_mae="ASUS TUF Gaming",
            modelo_placa_video="AMD Radeon RX 6600",
            memoria_ram="16GB",
            armazenamento="512GB SSD",
            modelo_fonte="Cooler Master 650W",
            modelo_gabinete="NZXT H210",
            modelo_hd="Seagate Barracuda 1TB",
            localizacao="Escritório 2",
            data_aquisicao="2023-05-01",
            ),
            Computador(
            numero_de_patrimonio="A_006",
            modelo_processador="Intel Core i3",
            modelo_placa_mae="Gigabyte B460M",
            modelo_placa_video="Intel UHD Graphics 630",
            memoria_ram="8GB",
            armazenamento="256GB SSD",
            modelo_fonte="EVGA 500W",
            modelo_gabinete="Thermaltake Versa H18",
            modelo_hd="Western Digital Blue 500GB",
            localizacao="Recepção",
            data_aquisicao="2023-06-01",
            ),
            Computador(
            numero_de_patrimonio="A_007",
            modelo_processador="AMD Ryzen 9",
            modelo_placa_mae="MSI X570 Gaming Plus",
            modelo_placa_video="NVIDIA GeForce RTX 3070",
            memoria_ram="64GB",
            armazenamento="2TB SSD",
            modelo_fonte="Corsair 1000W",
            modelo_gabinete="Phanteks Eclipse P400A",
            modelo_hd="Seagate IronWolf 4TB",
            localizacao="Sala de Desenvolvimento",
            data_aquisicao="2023-07-01",
            ),
            Computador(
            numero_de_patrimonio="A_008",
            modelo_processador="Intel Core i5",
            modelo_placa_mae="ASUS Prime B560M",
            modelo_placa_video="NVIDIA GeForce GTX 1650",
            memoria_ram="16GB",
            armazenamento="512GB SSD",
            modelo_fonte="Cooler Master 550W",
            modelo_gabinete="Corsair Carbide 275R",
            modelo_hd="Western Digital Blue 1TB",
            localizacao="Escritório 3",
            data_aquisicao="2023-08-01",
            ),
            Computador(
            numero_de_patrimonio="A_009",
            modelo_processador="AMD Ryzen 3",
            modelo_placa_mae="Gigabyte A320M",
            modelo_placa_video="AMD Radeon Vega 8",
            memoria_ram="8GB",
            armazenamento="256GB SSD",
            modelo_fonte="Thermaltake 450W",
            modelo_gabinete="Cooler Master MasterBox Q300L",
            modelo_hd="Seagate Barracuda 500GB",
            localizacao="Sala de Treinamento",
            data_aquisicao="2023-09-01",
            ),
            Computador(
            numero_de_patrimonio="A_010",
            modelo_processador="Intel Core i7",
            modelo_placa_mae="MSI MPG Z490",
            modelo_placa_video="NVIDIA GeForce RTX 3060",
            memoria_ram="32GB",
            armazenamento="1TB SSD",
            modelo_fonte="EVGA 750W",
            modelo_gabinete="NZXT H510 Elite",
            modelo_hd="Western Digital Black 2TB",
            localizacao="Sala de Conferências",
            data_aquisicao="2023-10-01",
            ),
            Computador(
            numero_de_patrimonio="A_011",
            modelo_processador="AMD Ryzen 5",
            modelo_placa_mae="ASUS ROG Strix B550-F",
            modelo_placa_video="AMD Radeon RX 5500 XT",
            memoria_ram="16GB",
            armazenamento="512GB SSD",
            modelo_fonte="Corsair 650W",
            modelo_gabinete="Fractal Design Define R5",
            modelo_hd="Seagate Barracuda 1TB",
            localizacao="Escritório 4",
            data_aquisicao="2023-11-01",
            ),
            Computador(
            numero_de_patrimonio="A_012",
            modelo_processador="Intel Core i9",
            modelo_placa_mae="ASRock Z490 Phantom Gaming",
            modelo_placa_video="NVIDIA GeForce RTX 3080 Ti",
            memoria_ram="64GB",
            armazenamento="2TB SSD",
            modelo_fonte="Seasonic 850W",
            modelo_gabinete="Lian Li Lancool II",
            modelo_hd="Western Digital Black 4TB",
            localizacao="Sala de Diretores",
            data_aquisicao="2023-12-01",
            ),
            Computador(
            numero_de_patrimonio="A_013",
            modelo_processador="AMD Ryzen 7",
            modelo_placa_mae="MSI B550M PRO-VDH",
            modelo_placa_video="AMD Radeon RX 6800",
            memoria_ram="32GB",
            armazenamento="1TB SSD",
            modelo_fonte="Cooler Master 750W",
            modelo_gabinete="NZXT H510 Flow",
            modelo_hd="Seagate Barracuda 2TB",
            localizacao="Sala de Projetos",
            data_aquisicao="2024-01-01",
            ),
            Computador(
            numero_de_patrimonio="A_014",
            modelo_processador="Intel Core i3",
            modelo_placa_mae="Gigabyte H410M",
            modelo_placa_video="Intel UHD Graphics 630",
            memoria_ram="8GB",
            armazenamento="256GB SSD",
            modelo_fonte="EVGA 450W",
            modelo_gabinete="Thermaltake Core V1",
            modelo_hd="Western Digital Blue 500GB",
            localizacao="Recepção 2",
            data_aquisicao="2024-02-01",
            ),
            Computador(
            numero_de_patrimonio="A_015",
            modelo_processador="AMD Ryzen 9",
            modelo_placa_mae="ASUS TUF Gaming X570",
            modelo_placa_video="NVIDIA GeForce RTX 3090",
            memoria_ram="64GB",
            armazenamento="2TB SSD",
            modelo_fonte="Corsair 1000W",
            modelo_gabinete="Phanteks Enthoo Pro",
            modelo_hd="Seagate IronWolf 4TB",
            localizacao="Sala de Pesquisa",
            data_aquisicao="2024-03-01",
            ),
        ]

        equipamentos = [
            Equipamento(
            numero_de_patrimonio="E_001",
            modelo="Impressora HP LaserJet Pro",
            localizacao="Sala de Impressão",
            data_aquisicao="2023-01-15",
            tipo="Impressora",
            ),
            Equipamento(
            numero_de_patrimonio="E_002",
            modelo="Scanner Epson Perfection V600",
            localizacao="Sala de Digitalização",
            data_aquisicao="2023-02-10",
            tipo="Scanner",
            ),
            Equipamento(
            numero_de_patrimonio="E_003",
            modelo="Projetor BenQ TK850",
            localizacao="Sala de Conferências",
            data_aquisicao="2023-03-05",
            tipo="Projetor",
            ),
            Equipamento(
            numero_de_patrimonio="E_004",
            modelo="Switch Cisco SG350",
            localizacao="Sala de Servidores",
            data_aquisicao="2023-04-20",
            tipo="Switch de Rede",
            ),
            Equipamento(
            numero_de_patrimonio="E_005",
            modelo="Telefone IP Yealink T46S",
            localizacao="Recepção",
            data_aquisicao="2023-05-15",
            tipo="Telefone IP",
            ),
            Equipamento(
            numero_de_patrimonio="E_006",
            modelo="Monitor Dell UltraSharp U2723QE",
            localizacao="Escritório 1",
            data_aquisicao="2023-06-25",
            tipo="Monitor",
            ),
            Equipamento(
            numero_de_patrimonio="E_007",
            modelo="Nobreak APC Back-UPS Pro 1500VA",
            localizacao="Sala de TI",
            data_aquisicao="2023-07-30",
            tipo="Nobreak",
            ),
        ]

        manutencoes_computadores = [
            Manutencoes_Computadores(
            Computador=computadores[0],
            data_manutencao="2023-01-20",
            descricao="Troca de HD",
            ),
            Manutencoes_Computadores(
            Computador=computadores[1],
            data_manutencao="2023-02-15",
            descricao="Atualização de memória RAM",
            ),
            Manutencoes_Computadores(
            Computador=computadores[2],
            data_manutencao="2023-03-10",
            descricao="Limpeza interna e troca de pasta térmica",
            ),
        ]

        manutencoes_equipamentos = [
            Manutencoes_Equipamentos(
            Equipamento=equipamentos[0],
            data_manutencao="2023-01-25",
            descricao="Troca de toner",
            ),
            Manutencoes_Equipamentos(
            Equipamento=equipamentos[1],
            data_manutencao="2023-02-20",
            descricao="Atualização de driver",
            ),
            Manutencoes_Equipamentos(
            Equipamento=equipamentos[2],
            data_manutencao="2023-03-15",
            descricao="Calibração do projetor",
            ),
        ]

        Computador.objects.bulk_create(computadores)
        Equipamento.objects.bulk_create(equipamentos)
        Manutencoes_Equipamentos.objects.bulk_create(manutencoes_equipamentos)
        Manutencoes_Computadores.objects.bulk_create(manutencoes_computadores)